#!/usr/bin/bash

source venv/bin/activate

pycodestyle aims tests
if [ $? -ne "0" ]
then
    exit 1
fi

mypy aims/ tests/
if [ $? -ne "0" ]
then
    exit 2
fi

pyflakes3 aims tests
if [ $? -ne "0" ]
then
    exit 3
fi

cd tests
python -m unittest
if [ $? -ne "0" ]
then
    exit 4
fi
